### PR TITLE
UMake pre before directory created

### PR DESCRIPTION
**Pull request by Lawendt**
- Build method of the targets now create the path after pre-build actions are done.
- UMake with an option of executing post-build actions upon build
- Bundle version for iOS

### CODE REVIEW

**Comment by vamolessa** [comment]
Aaa way to go! There's an issue however: if it's invoked through UMakeCli, the post build actions are executed twice. I've been thinking about what you said another day and *always* executing post build action may be the way (and maybe having a BuildTarget copy without those post build actions if needed).

Also, would you mind using tabs instead of space when PRing? This will help a lot keeping the codebase consistent.

Thank you so much again :)

**Comment by Lawendt** [comment]
I did not tried with CLI so I didn't noticed that 🤔
If you want to make these changes and always executing post-build, I can do that~ 
And yeah, asap I will change space to tabs!

**Comment by Lawendt** [comment]
When you see it will execute post-build on UMakeCli is when the user execute `BuildAndPostBuild`, right? 
I don't know if I can just delete this because I imagine you have a CI or automate build system working with that. Right now having this boolean in UMake for easy use on Unity is fine for my use, and I also did the default value `false`, so I think it will have no problem. 🤔

What do you think?

**Comment by Lawendt** [comment]
I removed the post-build from this, then this change is related to the change of the pre-build action before the directory is created!

**Pull request merged**
